/*SI LA TABLA NO ESTÁ CREADA SE PUEDE AGREGAR LA PATICIÓN EN LA MISMA SENTENCIA CREATE*/
CREATE  TABLE IF NOT EXISTS `mydb`.`tabla` (
  `id_tabla` INT NOT NULL ,
  `tipo` ENUM('1','2','3') NULL ,
  PRIMARY KEY (`id_tabla`) ,
  INDEX `index` (`tipo` ASC) 
 )
ENGINE = InnoDB 
PARTITION BY HASH(tipo) 
PARTITIONS 3


/*SI LA TABLA ESTA CREADA HAY QUE MODIFICARLA*/
ALTER TABLE `mydb`.`tabla`
PARTITION BY HASH(tipo) 
PARTITIONS 3;